Add option to specify go version from go.mod or go.work
WillAbides/setup-go-faster pull request #21
Opened 2023-08-08 12:59 UTC by manel-bc

Something I've been missing from actions/setup-go.

It makes sure at least one of the inputs `go-version` or `go-version-file` is set, with the former taking precedence.

2023-08-08 17:11 UTC, WillAbides commented
Thanks. I just discovered that feature of setup-go recently and was thinking about adding this. I'll review it later today or in the morning.

2023-08-08 23:06 UTC, WillAbides requested changes
The code looks good. I like that you used perl for the regex. Since it's a dependency anyway, we might as well use it for what it is good for 😄 

I requested a couple of changes. Let me know if you have any questions or want help implementing them.

I'm not 100% sure if my suggestion of `>=1.N` works with [semver-select](https://github.com/WillAbides/semver-select). I'll check on that and report back if there are issues.

2023-08-08 23:06 UTC, WillAbides commented on src/lib
> +  perl -nle 'print $1 if /^go (\d\.\d+)/' < "$go_file_path"
I think it is valid to have space before "go" and more than one space between "go" and the version constraint.

[The doc](https://go.dev/ref/mod#go-mod-file-go) also gives `1.21rc1` as an example value, so we should capture to the end of the token.

It also says that 1.16 is assumed when there is no directive. So either select_go_version_from_file should return "1.16" when there is no match or `src/run` should set it to "1.16" when `select_go_version_from_file` returns nothing.

2023-08-08 23:06 UTC, WillAbides commented on src/lib
> +    return
```suggestion
    return 1
```

It should return non-zero to prevent the run from continuing.

2023-08-08 23:06 UTC, WillAbides commented on src/run
> +  constraint="$(select_go_version_from_file "$GITHUB_WORKSPACE/$GO_VERSION_FILE")"
I'm not sure that using the output of `select_go_version_from_file` as the constraint is the right thing to do here. The go.mod doc says the version is the minimum version to use. So it seems like when the directive is `1.18` the constraint should be `>=1.18` and `1.21rc1` should be `>=1.21rc1`.

I think sticking a `>=` at the beginning of the constraint is all we need to do here. It may not work quite right in the time between go1.22rc1 and go1.22, but this PR doesn't need to address that.

2023-08-09 09:50 UTC, manel-bc commented on src/run
> +  constraint="$(select_go_version_from_file "$GITHUB_WORKSPACE/$GO_VERSION_FILE")"
Added `>=`

2023-08-09 09:51 UTC, manel-bc commented on src/lib
> +  perl -nle 'print $1 if /^go (\d\.\d+)/' < "$go_file_path"
The new regexp should cater for that, and made 1.16 the default in case of no match

2023-08-09 15:30 UTC, WillAbides requested changes
Thanks for updating. Just one more change to the regex. I also need to update semver-select to make it work with release candidates.

2023-08-09 15:30 UTC, WillAbides commented on src/lib
> +  found_version="$(perl -nle 'print $1 if /^\s*go (\d\.\d+.*$)/' < "$go_file_path")"
After looking at the spec a little more, it allows comments on the same line after the go directive, so the regex should end with optional whitespace followed by either $ or `//`.

```suggestion
  found_version="$(perl -nle 'print $1 if /^\s*go\s+(\S+)\s*(?:$|(?:\/\/))/' < "$go_file_path")"
```

This also updates it to match any non-whitespace because that's what the spec says. If it doesn't match what you had it will end up failing when it is passed to semver-select, but I would rather have it fail there than to silently not match and use the default.

2023-08-10 13:40 UTC, WillAbides approved these changes
LGTM. I'm going to merge this then make a PR of my own to update the semver-select version before doing a release.

2023-08-10 13:40 UTC, merged

2023-08-11 12:17 UTC, manel-bc commented
Nice, thanks :)